In [19]:
import numpy as np
a = np.arange(30).reshape(3,10)
a.dtype
b = np.array([1,2,3])
c = np.array([1,2,3],dtype=float)
np.ones((3,4),dtype=int)
a = np.ones((2,3),dtype=int)
b = np.ones((3,2),dtype=int)
c = np.dot(a,b)
print c

[[3 3]
 [3 3]]


In [46]:
import numpy
#print dir(numpy)
a = numpy.random.random((3,1))*10
print a
b = numpy.linspace(0,3.14,3)
print numpy.amin(a)
print numpy.argmin(a)


[[ 1.42872608]
 [ 7.95792223]
 [ 7.66965498]]
1.42872607506
0


In [32]:
import numpy as np
import random
a = np.zeros((3,3),dtype=int)
a[2][1]=1
row,col = a.shape
for r in range(row):
    for c in range(col):
        a[r][c] = random.choice([0,1])


b = np.ones((3,3),dtype=int)
c = np.vstack((b,a))
print c
print a[0].append(b[0])

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 1 0]
 [1 1 0]
 [1 0 1]]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [57]:
import numpy as np
x = np.array([1,2,3],dtype=int)
x

array([1, 2, 3])